"""Compatibility facade while the proven Xiaozhi connection is split by owner."""

from ..xiaozhi_runtime import (
    XIAOZHI_OPUS_APPLICATION,
    XIAOZHI_OUTPUT_SAMPLE_RATE,
    XIAOZHI_PLAYBACK_PREBUFFER_PACKETS,
    XIAOZHI_UDP_PROFILE,
    XIAOZHI_WSS_PROFILE,
    SharedSessionAdmission,
    XiaozhiConnection,
    XiaozhiHello,
    XiaozhiMessageTooLarge,
    XiaozhiOpusCodec,
    XiaozhiOverloadedError,
    XiaozhiProtocolError,
    XiaozhiSessionRegistry,
    normalize_device_id,
    parse_client_hello,
    parse_client_message,
    resolve_xiaozhi_device_id,
)

__all__ = [
    "XIAOZHI_OPUS_APPLICATION",
    "XIAOZHI_OUTPUT_SAMPLE_RATE",
    "XIAOZHI_PLAYBACK_PREBUFFER_PACKETS",
    "XIAOZHI_UDP_PROFILE",
    "XIAOZHI_WSS_PROFILE",
    "SharedSessionAdmission",
    "XiaozhiConnection",
    "XiaozhiHello",
    "XiaozhiMessageTooLarge",
    "XiaozhiOpusCodec",
    "XiaozhiOverloadedError",
    "XiaozhiProtocolError",
    "XiaozhiSessionRegistry",
    "normalize_device_id",
    "parse_client_hello",
    "parse_client_message",
    "resolve_xiaozhi_device_id",
]
